#!/usr/bin/env bash
#
# Entrypoint of the Docker image having the option switch.
#
# Copyright (c) 2017, Groupon, Inc.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met:
#
# Redistributions of source code must retain the above copyright notice,
# this list of conditions and the following disclaimer.
#
# Redistributions in binary form must reproduce the above copyright
# notice, this list of conditions and the following disclaimer in the
# documentation and/or other materials provided with the distribution.
#
# Neither the name of GROUPON nor the names of its contributors may be
# used to endorse or promote products derived from this software without
# specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
# IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
# TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
# PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
# TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
# PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
# LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
# NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# shellcheck disable=SC1091
source /silo/silo_functions.sh

check_compatibility

case "$1" in
  "--version")
    get_silo_info
    ;;
  "--install")
    # shellcheck disable=SC1091
    source /silo/install.sh
    ;;
  "--run")
    create_runner "$@"
    ;;
  "--switch")
    shift
    switch_ansible_version "$@"
    ;;
  "--shell")
    prepare_user
    prepare_ansible
    prepare_environment
    prepare_ansible_lint
    shift
    if [[ $# -eq 0 ]]; then
      run_as_user_with_SSH /bin/bash
    else
      run_as_user_with_SSH /bin/bash -c "$*"
    fi
    ;;
  "--bundle")
    bundle_create "$2"
    ;;
  "--help"|"")
    cat /silo/help.txt
    if [[ -z "$1" ]]; then
      exit "${EX_USAGE}"
    fi
    ;;
  *)
    prepare_user
    prepare_ansible
    prepare_environment
    prepare_ansible_lint
    cd /home/user/playbooks || exit
    if [[ -x "/silo/userspace/ansible/bin/$1" ]]; then
      ansible_command="$1"
      shift
      run_as_user_with_SSH "${ansible_command}" "$@"
    elif [[ -x "/silo/userspace/bin/$1" ]]; then
      command="$1"
      shift
      run_as_user_with_SSH "${command}" "$@"
    else
      echo "Unknown option: $1" >&2
      cat /silo/help.txt
      exit "${EX_USAGE}"
    fi
    ;;
esac
